version: '3'
services: 
    db:
        image: 'mongo'
        container_name: 'aurl-mongodb'
        volumes:
            - ./data/mongo:/data/db
            - ./data/dump:/dump
            - ./data/backup:/backup
#       ports: 
#           - '27017:27017'
    web:
        image: 'simbafs/aurl:1.0'
        container_name: 'aurl-web'
        environment:
            DB: 'mongodb://db:27017/aurl'
            BASEURL: 'https://your.domain'
            backdoor: 'https://backdoor.token'
            admin: 'admin.token'
            PORT: '3000' #optional
            
            appName: "AURL"
            title: "Url Shortener"
            subtitle: ""
        ports: 
            - '3000:3000'
